name: Deploy to CloudHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    env:
      ENV_CLIENT_SECRET: ${{secrets.ENV_CLIENT_SECRET}}
      ENV_CLIENT_ID: ${{secrets.ENV_CLIENT_ID}}
      CONNECTEDAPP_CLIENT_ID: ${{secrets.CONNECTEDAPP_CLIENT_ID}}
      CONNECTEDAPP_CLIENT_SECRET: ${{secrets.CONNECTEDAPP_CLIENT_SECRET}}
      ENCRYPTIO_KEY: ${{secrets.ENCRYPTIO_KEY}}

    steps:
    - name: Downloading Code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and Deploy to CH with Maven
      run: mvn -B clean deploy -DmuleDeploy -s settings.xml --file pom.xml -Dmule.env=dev -Dencryption.key=${env.ENCRYPTIO_KEY} -Danypoint.platform.client_id=${env.ENV_CLIENT_ID} -Danypoint.platform.client_secret=${env.ENV_CLIENT_SECRET} -DclientId=${env.CONNECTEDAPP_CLIENT_ID} -DclientSec=${env.CONNECTEDAPP_CLIENT_SECRET}

